import { categories, spots, getSpot, getCategory } from './data/spots.js';
import { courses, getCourse } from './data/courses.js';
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]));
const tags=a=>`<div class="tags">${a.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;
function nav(view,id){location.hash=id?`${view}/${id}`:view}
function home(){app.innerHTML=`<section class="hero"><p class="eyebrow">福井県南越前町</p><h1>歩いて、味わって、<br>今庄を知る。</h1><p>宿場町、鉄道遺産、おろしそば。今庄の魅力をスマートフォンひとつで案内します。</p><div class="hero-stats"><strong>${spots.length}</strong><span>登録スポット</span></div></section><section class="section"><div class="section-title"><h2>目的から探す</h2><small>9 categories</small></div><div class="category-grid">${categories.map(c=>`<button class="category-card" data-go="${c.route?'courses':`category/${c.key}`}"><span class="category-icon">${c.icon}</span><strong>${c.label}</strong><small>${c.description}</small></button>`).join('')}</div></section><section class="section featured"><div class="section-title"><h2>まずはこのコース</h2></div><button class="feature-card" data-go="course/soba-walk"><div><span class="pill">徒歩・約60〜90分</span><h3>今庄おろしそば巡り</h3><p>宿場町を歩きながら、徒歩圏の5店舗を巡ります。</p></div><span class="feature-icon">🍜</span></button></section>`;bind();}
function category(key){const c=getCategory(key);const list=spots.filter(s=>s.category===key);app.innerHTML=`<button class="back-btn" data-go="home">← ホーム</button><div class="page-heading"><span>${c?.icon||'📍'}</span><div><p>${esc(c?.description||'')}</p><h1>${esc(c?.label||'準備中')}</h1></div></div><label class="search-box"><span>⌕</span><input id="search" type="search" placeholder="名前・タグで検索"></label><p class="result-count"><span id="count">${list.length}</span>件</p><div id="spotList" class="spot-list">${spotCards(list)}</div>`;document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value;const f=list.filter(s=>`${s.name} ${s.subcategory} ${s.tags.join(' ')}`.includes(q));document.querySelector('#spotList').innerHTML=spotCards(f);document.querySelector('#count').textContent=f.length;bind();});bind();}
const spotCards=list=>list.map(s=>`<button class="spot-card" data-go="spot/${s.id}"><div class="spot-thumb"><span>${esc(s.name.slice(0,1))}</span></div><div class="spot-body"><small>${esc(s.subcategory)}</small><h3>${esc(s.name)}</h3>${tags(s.tags.slice(0,3))}</div><span class="chevron">›</span></button>`).join('');
function spot(id){const s=getSpot(id),c=s&&getCategory(s.category);if(!s)return home();const map=s.lat?`https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}`:'';app.innerHTML=`<button class="back-btn" data-go="category/${s.category}">← 戻る</button><article class="detail"><div class="detail-visual"><span>${c.icon}</span><small>PHOTO COMING SOON</small></div><div class="detail-content"><p class="eyebrow">${c.label} / ${esc(s.subcategory)}</p><h1>${esc(s.name)}</h1>${tags(s.tags)}<section class="info-block"><h2>紹介</h2><p>このスポットの紹介文は現在準備中です。今後、見どころや歴史、利用案内を追加できます。</p></section><section class="info-block"><h2>基本情報</h2><dl><div><dt>カテゴリ</dt><dd>${c.label}</dd></div><div><dt>サブカテゴリ</dt><dd>${esc(s.subcategory)}</dd></div>${s.lat?`<div><dt>緯度・経度</dt><dd>${s.lat}, ${s.lng}</dd></div>`:''}</dl></section>${map?`<a href="${map}" target="_blank" rel="noopener" class="primary-button">Googleマップで開く</a>`:'<button class="primary-button disabled" disabled>地図情報は準備中</button>'}</div></article>`;bind();}
function courseList(){app.innerHTML=`<button class="back-btn" data-go="home">← ホーム</button><div class="page-heading"><span>🚶</span><div><p>今庄をテーマ別に楽しむ</p><h1>モデルコース</h1></div></div><div class="course-list">${courses.map(c=>`<button class="course-card" data-go="course/${c.id}"><span class="course-icon">${c.icon}</span><div><div class="course-meta"><span>${c.transport}</span><span>${c.duration}</span><span>${c.spots.length}スポット</span></div><h2>${c.title}</h2><p>${c.lead}</p></div><span class="chevron">›</span></button>`).join('')}</div>`;bind();}
function course(id){const c=getCourse(id);if(!c)return courseList();const ss=c.spots.map(getSpot).filter(Boolean);app.innerHTML=`<button class="back-btn" data-go="courses">← コース一覧</button><article class="course-detail"><div class="course-hero"><span>${c.icon}</span><p>${c.transport}・${c.duration}</p><h1>${c.title}</h1><p>${c.lead}</p></div><section class="section"><div class="section-title"><h2>コース順</h2><small>${ss.length} spots</small></div><ol class="route-list">${ss.map((s,i)=>`<li><span class="route-number">${i+1}</span><button data-go="spot/${s.id}"><small>${s.subcategory}</small><strong>${s.name}</strong></button></li>`).join('')}</ol></section><div class="notice"><strong>ご利用前に</strong><p>営業日・営業時間、道路状況、季節による通行規制などは事前に各施設へご確認ください。</p></div></article>`;bind();}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',()=>{location.hash=el.dataset.go}));}
function render(){const [view,id]=(location.hash.slice(1)||'home').split('/');if(view==='category')category(id);else if(view==='spot')spot(id);else if(view==='courses')courseList();else if(view==='course')course(id);else home();window.scrollTo(0,0)}
window.addEventListener('hashchange',render);document.querySelector('#homeBtn').addEventListener('click',()=>nav('home'));document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>nav('category',b.dataset.category)));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
